# Generated by Django 6.1.1 on 2026-09-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('commerce', 'Commerce'), ('clinique', 'Clinique'), ('restaurant', 'Restaurant'), ('ecole', 'École'), ('atelier', 'Atelier'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], default='entreprise', max_length=30, verbose_name='Secteur')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Technologies')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Client')),
                ('project_url', models.URLField(blank=True, verbose_name='Lien du projet')),
                ('featured', models.BooleanField(default=False, verbose_name="Afficher sur l'accueil")),
                ('is_active', models.BooleanField(default=True, verbose_name='Projet actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
